GET http://localhost:8080/movies
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/screenings/Blade%20Runner
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/screenings/Oppenheimer
Content-Type: application/json
Accept: application/json

###

GET http://localhost:8080/screenings/dca8089a-4583-4941-8e65-56effa6b99/availableSeats
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/reservation
Content-Type: application/json
Accept: application/json

{
  "movieName": "Blade Runner",
  "time": "2023-07-30T12:30:00.000Z",
  "reservationLines": [
    {
      "seat": {
        "rowNo": 1,
        "columnNo": 1,
        "hallNo": 1
      },
      "discountType": "NORMAL"
    },
    {
      "seat": {
        "rowNo": 1,
        "columnNo": 3,
        "hallNo": 1
      },
      "discountType": "CHILD"
    }
  ]
}

###

GET http://localhost:8080/reservation/4cb87c58-2b88-4e47-b155-d604944ebd58
Content-Type: application/json
Accept: application/json

###

PUT http://localhost:8080/reservation/4cb87c58-2b88-4e47-b155-d604944ebd58/pay
Content-Type: application/json
Accept: application/json

###

PUT http://localhost:8080/reservation/4cb87c58-2b88-4e47-b155-d604944ebd58/cancel
Content-Type: application/json
Accept: application/json