GET http://localhost:8080/movies
Content-Type: application/json
Accept: application/json

###

POST http://localhost:8080/reservation
Content-Type: application/json
Accept: application/json

{
  "movieName": "Blade Runner",
  "time": "2023-07-30T12:30:00.000Z",
  "reservationLines": [
    {
      "seat": {
        "rowNo": 1,
        "columnNo": 1,
        "hallNo": 1
      },
      "discountType": "NORMAL"
    }
  ]
}

###

GET http://localhost:8080/reservation/f38fe94a-b51c-4e2d-998b-1c33104ce100
Content-Type: application/json
Accept: application/json